// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQAoleiiVjJ0wTWCuD6mYoP4dcOqFJPi8',
    appId: '1:630656181963:web:8eafd9b320911df86a5d4e',
    messagingSenderId: '630656181963',
    projectId: 'eol-7dbb4',
    authDomain: 'eol-7dbb4.firebaseapp.com',
    storageBucket: 'eol-7dbb4.firebasestorage.app',
    measurementId: 'G-XQ75C5DN4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEwNp9iJxVYVd9rwrl6IMeoheR_F2zOXI',
    appId: '1:630656181963:android:33ef79c3d9e78b416a5d4e',
    messagingSenderId: '630656181963',
    projectId: 'eol-7dbb4',
    storageBucket: 'eol-7dbb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBONZSYgfbXHszPsLDRJcCydd2J4pui_oU',
    appId: '1:630656181963:ios:0684d9f2213e7aa76a5d4e',
    messagingSenderId: '630656181963',
    projectId: 'eol-7dbb4',
    storageBucket: 'eol-7dbb4.firebasestorage.app',
    iosBundleId: 'com.example.eolApp',
  );
}
