// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:simplify/features/community/data/models/pending_message.dart';
import 'package:simplify/features/notes/data/models/note_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NoteAdapter());
    registerAdapter(PendingMessageAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NoteAdapter());
    registerAdapter(PendingMessageAdapter());
  }
}
